# Generated by Django 5.2.1 on 2025-05-18 20:23

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('nome_bordado', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(max_length=20)),
                ('tamanho_faixa', models.CharField(max_length=10)),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='Faixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ordem', models.IntegerField(unique=True)),
                ('programa', models.FileField(blank=True, null=True, upload_to='programas/')),
            ],
            options={
                'verbose_name': 'Faixa',
                'verbose_name_plural': 'Faixas',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_avaliacao', models.DateTimeField()),
                ('nota_final', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('aprovado', models.BooleanField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='alunos.aluno')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'ordering': ['-data_avaliacao'],
            },
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='certificados/')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='alunos.aluno')),
                ('avaliacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='alunos.avaliacao')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'ordering': ['-data_emissao'],
            },
        ),
        migrations.AddField(
            model_name='aluno',
            name='faixa_atual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alunos_atual', to='alunos.faixa'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='faixa_proxima',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alunos_proxima', to='alunos.faixa'),
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('tipo', models.CharField(choices=[('teorica', 'Teórica'), ('pratica', 'Prática'), ('kata', 'Kata'), ('randori', 'Randori')], max_length=20)),
                ('peso', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('prioritaria', models.BooleanField(default=False)),
                ('faixa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questoes', to='alunos.faixa')),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
                'ordering': ['faixa__ordem', 'texto'],
            },
        ),
        migrations.CreateModel(
            name='RespostaAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conceito', models.IntegerField(blank=True, choices=[(0, 'Não Atende'), (1, 'Atende Parcialmente'), (2, 'Atende'), (3, 'Supera')], null=True)),
                ('observacao', models.TextField(blank=True)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='alunos.avaliacao')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alunos.questao')),
            ],
            options={
                'verbose_name': 'Resposta',
                'verbose_name_plural': 'Respostas',
                'ordering': ['questao__faixa__ordem', 'questao__texto'],
            },
        ),
    ]
