# Generated by Django 5.2.1 on 2025-05-19 01:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('nome_bordado', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('tamanho_faixa', models.CharField(max_length=10)),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='ConceitoAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(choices=[('ND', 'Necessário Desenvolvimento'), ('R', 'Regular'), ('B', 'Bom'), ('MB', 'Muito Bom'), ('E', 'Excelente')], max_length=2, unique=True)),
                ('descricao', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Conceito de Avaliação',
                'verbose_name_plural': 'Conceitos de Avaliação',
            },
        ),
        migrations.CreateModel(
            name='EventoExame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('requisitos', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Faixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ordem', models.IntegerField(unique=True)),
                ('preco', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descricao', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('programa', models.FileField(blank=True, null=True, upload_to='programas/')),
            ],
            options={
                'verbose_name': 'Faixa',
                'verbose_name_plural': 'Faixas',
                'ordering': ['ordem'],
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('dias', models.CharField(blank=True, max_length=100)),
                ('horarios', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True)),
                ('avaliador', models.CharField(blank=True, max_length=100)),
                ('observacoes', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('aprovado', models.BooleanField(default=False)),
                ('nota_final', models.FloatField(blank=True, null=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='alunos.aluno')),
                ('conceito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='alunos.conceitoavaliacao')),
                ('faixa_atual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes_atual', to='alunos.faixa')),
                ('faixa_proxima', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes_proxima', to='alunos.faixa')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='certificados/')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='alunos.aluno')),
                ('avaliacao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='alunos.avaliacao')),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'ordering': ['-data_emissao'],
            },
        ),
        migrations.AddField(
            model_name='aluno',
            name='faixa_atual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alunos_atual', to='alunos.faixa'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='faixa_proxima',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alunos_proxima', to='alunos.faixa'),
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('natureza', models.CharField(choices=[('tecnica', 'Técnica'), ('historia', 'História'), ('regras', 'Regras'), ('filosofia', 'Filosofia'), ('etica', 'Ética')], max_length=20)),
                ('ativa', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('faixa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alunos.faixa')),
            ],
            options={
                'verbose_name': 'Questão',
                'verbose_name_plural': 'Questões',
                'ordering': ['faixa', 'natureza'],
            },
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='questoes',
            field=models.ManyToManyField(blank=True, related_name='avaliacoes', to='alunos.questao'),
        ),
        migrations.CreateModel(
            name='RespostaAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conceito', models.IntegerField(blank=True, choices=[(0, 'Não Atende'), (1, 'Atende Parcialmente'), (2, 'Atende'), (3, 'Supera')], null=True)),
                ('observacao', models.TextField(blank=True)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='alunos.avaliacao')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='alunos.questao')),
            ],
            options={
                'verbose_name': 'Resposta',
                'verbose_name_plural': 'Respostas',
                'ordering': ['questao__faixa__ordem', 'questao__texto'],
            },
        ),
        migrations.AddField(
            model_name='aluno',
            name='turma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='alunos', to='alunos.turma'),
        ),
        migrations.AddConstraint(
            model_name='aluno',
            constraint=models.UniqueConstraint(fields=('nome_completo',), name='unique_aluno_nome_completo'),
        ),
    ]
