# Generated by Django 5.2.1 on 2025-05-18 20:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faixa',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='faixa',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='faixa',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='faixa',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
