# Generated by Django 5.2.1 on 2025-05-18 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_faixa_data_atualizacao_faixa_data_criacao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceitoAvaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(choices=[('ND', 'Necessário Desenvolvimento'), ('R', 'Regular'), ('B', 'Bom'), ('MB', 'Muito Bom'), ('E', 'Excelente')], max_length=2, unique=True)),
                ('descricao', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Conceito de Avaliação',
                'verbose_name_plural': 'Conceitos de Avaliação',
            },
        ),
        migrations.AlterModelOptions(
            name='avaliacao',
            options={'ordering': ['-data'], 'verbose_name': 'Avaliação', 'verbose_name_plural': 'Avaliações'},
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='aprovado',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='data_avaliacao',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='nota_final',
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='faixa_atual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes_atual', to='alunos.faixa'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='faixa_proxima',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='avaliacoes_proxima', to='alunos.faixa'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='conceito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='alunos.conceitoavaliacao'),
        ),
    ]
